// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLm6C9gaI0w56o5SaysLBDGuSMw-wKKM',
    appId: '1:276773021809:web:25444de5184a4cf3fc53d0',
    messagingSenderId: '276773021809',
    projectId: 'azerbaijan-travel-app',
    authDomain: 'azerbaijan-travel-app.firebaseapp.com',
    storageBucket: 'azerbaijan-travel-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnERrb__Iincj1zevy4i7W2njNrhyzXHc',
    appId: '1:276773021809:android:783091357736a7dbfc53d0',
    messagingSenderId: '276773021809',
    projectId: 'azerbaijan-travel-app',
    storageBucket: 'azerbaijan-travel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl2RgUMT5zhDZiGzZv_R-wCE8KyFAvBwc',
    appId: '1:276773021809:ios:c35e23885b00c5acfc53d0',
    messagingSenderId: '276773021809',
    projectId: 'azerbaijan-travel-app',
    storageBucket: 'azerbaijan-travel-app.appspot.com',
    iosClientId: '276773021809-7uphf0b9p458bcg6300eh43kaj9rvuia.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
